version: '3'

services:

  api-gatway:
    build: api-gateway-svc
    ports:
      - "8080:80"
  
  torch-model:
    build: torch-model-svc
    ports:
      - "8081:8000"

  xgb-model:
    build: xgb-model-svc
    ports:
      - "8082:8000"
