version: '3'
services:
  api1:
    build: .
    command: uvicorn main1:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  api2:
    build: .
    command: uvicorn main2:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
